import { Chapter } from './types';

export const SURAHS: Chapter[] = [
  { id: 1, nameArabic: 'الفاتحة', nameSimple: 'Al-Fatihah', nameEnglish: 'The Opening', revelationPlace: 'makkah', versesCount: 7, bismillahPre: false },
  { id: 2, nameArabic: 'البقرة', nameSimple: 'Al-Baqarah', nameEnglish: 'The Cow', revelationPlace: 'madinah', versesCount: 286, bismillahPre: true },
  { id: 3, nameArabic: 'آل عمران', nameSimple: 'Ali \'Imran', nameEnglish: 'Family of Imran', revelationPlace: 'madinah', versesCount: 200, bismillahPre: true },
  { id: 4, nameArabic: 'النساء', nameSimple: 'An-Nisa', nameEnglish: 'The Women', revelationPlace: 'madinah', versesCount: 176, bismillahPre: true },
  { id: 5, nameArabic: 'المائدة', nameSimple: 'Al-Ma\'idah', nameEnglish: 'The Table Spread', revelationPlace: 'madinah', versesCount: 120, bismillahPre: true },
  { id: 6, nameArabic: 'الأنعام', nameSimple: 'Al-An\'am', nameEnglish: 'The Cattle', revelationPlace: 'makkah', versesCount: 165, bismillahPre: true },
  { id: 7, nameArabic: 'الأعراف', nameSimple: 'Al-A\'raf', nameEnglish: 'The Heights', revelationPlace: 'makkah', versesCount: 206, bismillahPre: true },
  { id: 8, nameArabic: 'الأنفال', nameSimple: 'Al-Anfal', nameEnglish: 'The Spoils of War', revelationPlace: 'madinah', versesCount: 75, bismillahPre: true },
  { id: 9, nameArabic: 'التوبة', nameSimple: 'At-Tawbah', nameEnglish: 'The Repentance', revelationPlace: 'madinah', versesCount: 129, bismillahPre: false },
  { id: 10, nameArabic: 'يونس', nameSimple: 'Yunus', nameEnglish: 'Jonah', revelationPlace: 'makkah', versesCount: 109, bismillahPre: true },
  { id: 11, nameArabic: 'هود', nameSimple: 'Hud', nameEnglish: 'Hud', revelationPlace: 'makkah', versesCount: 123, bismillahPre: true },
  { id: 12, nameArabic: 'يوسف', nameSimple: 'Yusuf', nameEnglish: 'Joseph', revelationPlace: 'makkah', versesCount: 111, bismillahPre: true },
  { id: 13, nameArabic: 'الرعد', nameSimple: 'Ar-Ra\'d', nameEnglish: 'The Thunder', revelationPlace: 'madinah', versesCount: 43, bismillahPre: true },
  { id: 14, nameArabic: 'إبراهيم', nameSimple: 'Ibrahim', nameEnglish: 'Abraham', revelationPlace: 'makkah', versesCount: 52, bismillahPre: true },
  { id: 15, nameArabic: 'الحجر', nameSimple: 'Al-Hijr', nameEnglish: 'The Rocky Tract', revelationPlace: 'makkah', versesCount: 99, bismillahPre: true },
  { id: 16, nameArabic: 'النحل', nameSimple: 'An-Nahl', nameEnglish: 'The Bee', revelationPlace: 'makkah', versesCount: 128, bismillahPre: true },
  { id: 17, nameArabic: 'الإسراء', nameSimple: 'Al-Isra', nameEnglish: 'The Night Journey', revelationPlace: 'makkah', versesCount: 111, bismillahPre: true },
  { id: 18, nameArabic: 'الكهف', nameSimple: 'Al-Kahf', nameEnglish: 'The Cave', revelationPlace: 'makkah', versesCount: 110, bismillahPre: true },
  { id: 19, nameArabic: 'مريم', nameSimple: 'Maryam', nameEnglish: 'Mary', revelationPlace: 'makkah', versesCount: 98, bismillahPre: true },
  { id: 20, nameArabic: 'طه', nameSimple: 'Taha', nameEnglish: 'Ta-Ha', revelationPlace: 'makkah', versesCount: 135, bismillahPre: true },
  { id: 21, nameArabic: 'الأنبياء', nameSimple: 'Al-Anbiya', nameEnglish: 'The Prophets', revelationPlace: 'makkah', versesCount: 112, bismillahPre: true },
  { id: 22, nameArabic: 'الحج', nameSimple: 'Al-Hajj', nameEnglish: 'The Pilgrimage', revelationPlace: 'madinah', versesCount: 78, bismillahPre: true },
  { id: 23, nameArabic: 'المؤمنون', nameSimple: 'Al-Mu\'minun', nameEnglish: 'The Believers', revelationPlace: 'makkah', versesCount: 118, bismillahPre: true },
  { id: 24, nameArabic: 'النور', nameSimple: 'An-Nur', nameEnglish: 'The Light', revelationPlace: 'madinah', versesCount: 64, bismillahPre: true },
  { id: 25, nameArabic: 'الفرقان', nameSimple: 'Al-Furqan', nameEnglish: 'The Criterion', revelationPlace: 'makkah', versesCount: 77, bismillahPre: true },
  { id: 26, nameArabic: 'الشعراء', nameSimple: 'Ash-Shu\'ara', nameEnglish: 'The Poets', revelationPlace: 'makkah', versesCount: 227, bismillahPre: true },
  { id: 27, nameArabic: 'النمل', nameSimple: 'An-Naml', nameEnglish: 'The Ants', revelationPlace: 'makkah', versesCount: 93, bismillahPre: true },
  { id: 28, nameArabic: 'القصص', nameSimple: 'Al-Qasas', nameEnglish: 'The Stories', revelationPlace: 'makkah', versesCount: 88, bismillahPre: true },
  { id: 29, nameArabic: 'العنكبوت', nameSimple: 'Al-\'Ankabut', nameEnglish: 'The Spider', revelationPlace: 'makkah', versesCount: 69, bismillahPre: true },
  { id: 30, nameArabic: 'الروم', nameSimple: 'Ar-Rum', nameEnglish: 'The Romans', revelationPlace: 'makkah', versesCount: 60, bismillahPre: true },
  { id: 31, nameArabic: 'لقمان', nameSimple: 'Luqman', nameEnglish: 'Luqman', revelationPlace: 'makkah', versesCount: 34, bismillahPre: true },
  { id: 32, nameArabic: 'السجدة', nameSimple: 'As-Sajdah', nameEnglish: 'The Prostration', revelationPlace: 'makkah', versesCount: 30, bismillahPre: true },
  { id: 33, nameArabic: 'الأحزاب', nameSimple: 'Al-Ahzab', nameEnglish: 'The Combined Forces', revelationPlace: 'madinah', versesCount: 73, bismillahPre: true },
  { id: 34, nameArabic: 'سبأ', nameSimple: 'Saba', nameEnglish: 'Sheba', revelationPlace: 'makkah', versesCount: 54, bismillahPre: true },
  { id: 35, nameArabic: 'فاطر', nameSimple: 'Fatir', nameEnglish: 'The Originator', revelationPlace: 'makkah', versesCount: 45, bismillahPre: true },
  { id: 36, nameArabic: 'يس', nameSimple: 'Ya-Sin', nameEnglish: 'Ya-Sin', revelationPlace: 'makkah', versesCount: 83, bismillahPre: true },
  { id: 37, nameArabic: 'الصافات', nameSimple: 'As-Saffat', nameEnglish: 'Those who set the Ranks', revelationPlace: 'makkah', versesCount: 182, bismillahPre: true },
  { id: 38, nameArabic: 'ص', nameSimple: 'Sad', nameEnglish: 'The Letter Sad', revelationPlace: 'makkah', versesCount: 88, bismillahPre: true },
  { id: 39, nameArabic: 'الزمر', nameSimple: 'Az-Zumar', nameEnglish: 'The Troops', revelationPlace: 'makkah', versesCount: 75, bismillahPre: true },
  { id: 40, nameArabic: 'غافر', nameSimple: 'Ghafir', nameEnglish: 'The Forgiver', revelationPlace: 'makkah', versesCount: 85, bismillahPre: true },
  { id: 41, nameArabic: 'فصلت', nameSimple: 'Fussilat', nameEnglish: 'Explained in Detail', revelationPlace: 'makkah', versesCount: 54, bismillahPre: true },
  { id: 42, nameArabic: 'الشورى', nameSimple: 'Ash-Shura', nameEnglish: 'The Consultation', revelationPlace: 'makkah', versesCount: 53, bismillahPre: true },
  { id: 43, nameArabic: 'الزخرف', nameSimple: 'Az-Zukhruf', nameEnglish: 'The Ornaments of Gold', revelationPlace: 'makkah', versesCount: 89, bismillahPre: true },
  { id: 44, nameArabic: 'الدخان', nameSimple: 'Ad-Dukhan', nameEnglish: 'The Smoke', revelationPlace: 'makkah', versesCount: 59, bismillahPre: true },
  { id: 45, nameArabic: 'الجاثية', nameSimple: 'Al-Jathiyah', nameEnglish: 'The Crouching', revelationPlace: 'makkah', versesCount: 37, bismillahPre: true },
  { id: 46, nameArabic: 'الأحقاف', nameSimple: 'Al-Ahqaf', nameEnglish: 'The Wind-Curved Sandhills', revelationPlace: 'makkah', versesCount: 35, bismillahPre: true },
  { id: 47, nameArabic: 'محمد', nameSimple: 'Muhammad', nameEnglish: 'Muhammad', revelationPlace: 'madinah', versesCount: 38, bismillahPre: true },
  { id: 48, nameArabic: 'الفتح', nameSimple: 'Al-Fath', nameEnglish: 'The Victory', revelationPlace: 'madinah', versesCount: 29, bismillahPre: true },
  { id: 49, nameArabic: 'الحجرات', nameSimple: 'Al-Hujurat', nameEnglish: 'The Rooms', revelationPlace: 'madinah', versesCount: 18, bismillahPre: true },
  { id: 50, nameArabic: 'ق', nameSimple: 'Qaf', nameEnglish: 'The Letter Qaf', revelationPlace: 'makkah', versesCount: 45, bismillahPre: true },
  { id: 51, nameArabic: 'الذاريات', nameSimple: 'Adh-Dhariyat', nameEnglish: 'The Winnowing Winds', revelationPlace: 'makkah', versesCount: 60, bismillahPre: true },
  { id: 52, nameArabic: 'الطور', nameSimple: 'At-Tur', nameEnglish: 'The Mount', revelationPlace: 'makkah', versesCount: 49, bismillahPre: true },
  { id: 53, nameArabic: 'النجم', nameSimple: 'An-Najm', nameEnglish: 'The Star', revelationPlace: 'makkah', versesCount: 62, bismillahPre: true },
  { id: 54, nameArabic: 'القمر', nameSimple: 'Al-Qamar', nameEnglish: 'The Moon', revelationPlace: 'makkah', versesCount: 55, bismillahPre: true },
  { id: 55, nameArabic: 'الرحمن', nameSimple: 'Ar-Rahman', nameEnglish: 'The Beneficent', revelationPlace: 'madinah', versesCount: 78, bismillahPre: true },
  { id: 56, nameArabic: 'الواقعة', nameSimple: 'Al-Waqi\'ah', nameEnglish: 'The Inevitable', revelationPlace: 'makkah', versesCount: 96, bismillahPre: true },
  { id: 57, nameArabic: 'الحديد', nameSimple: 'Al-Hadid', nameEnglish: 'The Iron', revelationPlace: 'madinah', versesCount: 29, bismillahPre: true },
  { id: 58, nameArabic: 'المجادلة', nameSimple: 'Al-Mujadila', nameEnglish: 'The Pleading Woman', revelationPlace: 'madinah', versesCount: 22, bismillahPre: true },
  { id: 59, nameArabic: 'الحشر', nameSimple: 'Al-Hashr', nameEnglish: 'The Exile', revelationPlace: 'madinah', versesCount: 24, bismillahPre: true },
  { id: 60, nameArabic: 'الممتحنة', nameSimple: 'Al-Mumtahanah', nameEnglish: 'She That Is to Be Examined', revelationPlace: 'madinah', versesCount: 13, bismillahPre: true },
  { id: 61, nameArabic: 'الصف', nameSimple: 'As-Saf', nameEnglish: 'The Ranks', revelationPlace: 'madinah', versesCount: 14, bismillahPre: true },
  { id: 62, nameArabic: 'الجمعة', nameSimple: 'Al-Jumu\'ah', nameEnglish: 'Friday', revelationPlace: 'madinah', versesCount: 11, bismillahPre: true },
  { id: 63, nameArabic: 'المنافقون', nameSimple: 'Al-Munafiqun', nameEnglish: 'The Hypocrites', revelationPlace: 'madinah', versesCount: 11, bismillahPre: true },
  { id: 64, nameArabic: 'التغابن', nameSimple: 'At-Taghabun', nameEnglish: 'The Mutual Disillusion', revelationPlace: 'madinah', versesCount: 18, bismillahPre: true },
  { id: 65, nameArabic: 'الطلاق', nameSimple: 'At-Talaq', nameEnglish: 'The Divorce', revelationPlace: 'madinah', versesCount: 12, bismillahPre: true },
  { id: 66, nameArabic: 'التحريم', nameSimple: 'At-Tahrim', nameEnglish: 'The Prohibition', revelationPlace: 'madinah', versesCount: 12, bismillahPre: true },
  { id: 67, nameArabic: 'الملك', nameSimple: 'Al-Mulk', nameEnglish: 'The Sovereignty', revelationPlace: 'makkah', versesCount: 30, bismillahPre: true },
  { id: 68, nameArabic: 'القلم', nameSimple: 'Al-Qalam', nameEnglish: 'The Pen', revelationPlace: 'makkah', versesCount: 52, bismillahPre: true },
  { id: 69, nameArabic: 'الحاقة', nameSimple: 'Al-Haqqah', nameEnglish: 'The Reality', revelationPlace: 'makkah', versesCount: 52, bismillahPre: true },
  { id: 70, nameArabic: 'المعارج', nameSimple: 'Al-Ma\'arij', nameEnglish: 'The Ascending Stairways', revelationPlace: 'makkah', versesCount: 44, bismillahPre: true },
  { id: 71, nameArabic: 'نوح', nameSimple: 'Nuh', nameEnglish: 'Noah', revelationPlace: 'makkah', versesCount: 28, bismillahPre: true },
  { id: 72, nameArabic: 'الجن', nameSimple: 'Al-Jinn', nameEnglish: 'The Jinn', revelationPlace: 'makkah', versesCount: 28, bismillahPre: true },
  { id: 73, nameArabic: 'المزمل', nameSimple: 'Al-Muzzammil', nameEnglish: 'The Enshrouded One', revelationPlace: 'makkah', versesCount: 20, bismillahPre: true },
  { id: 74, nameArabic: 'المدثر', nameSimple: 'Al-Muddaththir', nameEnglish: 'The Cloaked One', revelationPlace: 'makkah', versesCount: 56, bismillahPre: true },
  { id: 75, nameArabic: 'القيامة', nameSimple: 'Al-Qiyamah', nameEnglish: 'The Resurrection', revelationPlace: 'makkah', versesCount: 40, bismillahPre: true },
  { id: 76, nameArabic: 'الإنسان', nameSimple: 'Al-Insan', nameEnglish: 'The Man', revelationPlace: 'madinah', versesCount: 31, bismillahPre: true },
  { id: 77, nameArabic: 'المرسلات', nameSimple: 'Al-Mursalat', nameEnglish: 'The Emissaries', revelationPlace: 'makkah', versesCount: 50, bismillahPre: true },
  { id: 78, nameArabic: 'النبأ', nameSimple: 'An-Naba', nameEnglish: 'The Tidings', revelationPlace: 'makkah', versesCount: 40, bismillahPre: true },
  { id: 79, nameArabic: 'النازعات', nameSimple: 'An-Nazi\'at', nameEnglish: 'Those Who Drag Forth', revelationPlace: 'makkah', versesCount: 46, bismillahPre: true },
  { id: 80, nameArabic: 'عبس', nameSimple: '\'Abasa', nameEnglish: 'He Frowned', revelationPlace: 'makkah', versesCount: 42, bismillahPre: true },
  { id: 81, nameArabic: 'التكوير', nameSimple: 'At-Takwir', nameEnglish: 'The Overthrowing', revelationPlace: 'makkah', versesCount: 29, bismillahPre: true },
  { id: 82, nameArabic: 'الانفطار', nameSimple: 'Al-Infitar', nameEnglish: 'The Cleaving', revelationPlace: 'makkah', versesCount: 19, bismillahPre: true },
  { id: 83, nameArabic: 'المطففين', nameSimple: 'Al-Mutaffifin', nameEnglish: 'The Defrauding', revelationPlace: 'makkah', versesCount: 36, bismillahPre: true },
  { id: 84, nameArabic: 'الانشقاق', nameSimple: 'Al-Inshiqaq', nameEnglish: 'The Splitting Open', revelationPlace: 'makkah', versesCount: 25, bismillahPre: true },
  { id: 85, nameArabic: 'البروج', nameSimple: 'Al-Buruj', nameEnglish: 'The Mansions of the Stars', revelationPlace: 'makkah', versesCount: 22, bismillahPre: true },
  { id: 86, nameArabic: 'الطارق', nameSimple: 'At-Tariq', nameEnglish: 'The Morning Star', revelationPlace: 'makkah', versesCount: 17, bismillahPre: true },
  { id: 87, nameArabic: 'الأعلى', nameSimple: 'Al-A\'la', nameEnglish: 'The Most High', revelationPlace: 'makkah', versesCount: 19, bismillahPre: true },
  { id: 88, nameArabic: 'الغاشية', nameSimple: 'Al-Ghashiyah', nameEnglish: 'The Overwhelming', revelationPlace: 'makkah', versesCount: 26, bismillahPre: true },
  { id: 89, nameArabic: 'الفجر', nameSimple: 'Al-Fajr', nameEnglish: 'The Dawn', revelationPlace: 'makkah', versesCount: 30, bismillahPre: true },
  { id: 90, nameArabic: 'البلد', nameSimple: 'Al-Balad', nameEnglish: 'The City', revelationPlace: 'makkah', versesCount: 20, bismillahPre: true },
  { id: 91, nameArabic: 'الشمس', nameSimple: 'Ash-Shams', nameEnglish: 'The Sun', revelationPlace: 'makkah', versesCount: 15, bismillahPre: true },
  { id: 92, nameArabic: 'الليل', nameSimple: 'Al-Layl', nameEnglish: 'The Night', revelationPlace: 'makkah', versesCount: 21, bismillahPre: true },
  { id: 93, nameArabic: 'الضحى', nameSimple: 'Ad-Duha', nameEnglish: 'The Morning Hours', revelationPlace: 'makkah', versesCount: 11, bismillahPre: true },
  { id: 94, nameArabic: 'الشرح', nameSimple: 'Ash-Sharh', nameEnglish: 'The Relief', revelationPlace: 'makkah', versesCount: 8, bismillahPre: true },
  { id: 95, nameArabic: 'التين', nameSimple: 'At-Tin', nameEnglish: 'The Fig', revelationPlace: 'makkah', versesCount: 8, bismillahPre: true },
  { id: 96, nameArabic: 'العلق', nameSimple: 'Al-\'Alaq', nameEnglish: 'The Clot', revelationPlace: 'makkah', versesCount: 19, bismillahPre: true },
  { id: 97, nameArabic: 'القدر', nameSimple: 'Al-Qadr', nameEnglish: 'The Power', revelationPlace: 'makkah', versesCount: 5, bismillahPre: true },
  { id: 98, nameArabic: 'البينة', nameSimple: 'Al-Bayyinah', nameEnglish: 'The Clear Proof', revelationPlace: 'madinah', versesCount: 8, bismillahPre: true },
  { id: 99, nameArabic: 'الزلزلة', nameSimple: 'Az-Zalzalah', nameEnglish: 'The Earthquake', revelationPlace: 'madinah', versesCount: 8, bismillahPre: true },
  { id: 100, nameArabic: 'العاديات', nameSimple: 'Al-\'Adiyat', nameEnglish: 'The Courser', revelationPlace: 'makkah', versesCount: 11, bismillahPre: true },
  { id: 101, nameArabic: 'القارعة', nameSimple: 'Al-Qari\'ah', nameEnglish: 'The Calamity', revelationPlace: 'makkah', versesCount: 11, bismillahPre: true },
  { id: 102, nameArabic: 'التكاثر', nameSimple: 'At-Takathur', nameEnglish: 'The Rivalry in World Increase', revelationPlace: 'makkah', versesCount: 8, bismillahPre: true },
  { id: 103, nameArabic: 'العصر', nameSimple: 'Al-\'Asr', nameEnglish: 'The Declining Day', revelationPlace: 'makkah', versesCount: 3, bismillahPre: true },
  { id: 104, nameArabic: 'الهمزة', nameSimple: 'Al-Humazah', nameEnglish: 'The Traducer', revelationPlace: 'makkah', versesCount: 9, bismillahPre: true },
  { id: 105, nameArabic: 'الفيل', nameSimple: 'Al-Fil', nameEnglish: 'The Elephant', revelationPlace: 'makkah', versesCount: 5, bismillahPre: true },
  { id: 106, nameArabic: 'قريش', nameSimple: 'Quraysh', nameEnglish: 'Quraysh', revelationPlace: 'makkah', versesCount: 4, bismillahPre: true },
  { id: 107, nameArabic: 'الماعون', nameSimple: 'Al-Ma\'un', nameEnglish: 'The Small Kindness', revelationPlace: 'makkah', versesCount: 7, bismillahPre: true },
  { id: 108, nameArabic: 'الكوثر', nameSimple: 'Al-Kawthar', nameEnglish: 'The Abundance', revelationPlace: 'makkah', versesCount: 3, bismillahPre: true },
  { id: 109, nameArabic: 'الكافرون', nameSimple: 'Al-Kafirun', nameEnglish: 'The Disbelievers', revelationPlace: 'makkah', versesCount: 6, bismillahPre: true },
  { id: 110, nameArabic: 'النصر', nameSimple: 'An-Nasr', nameEnglish: 'The Divine Support', revelationPlace: 'madinah', versesCount: 3, bismillahPre: true },
  { id: 111, nameArabic: 'المسد', nameSimple: 'Al-Masad', nameEnglish: 'The Palm Fiber', revelationPlace: 'makkah', versesCount: 5, bismillahPre: true },
  { id: 112, nameArabic: 'الإخلاص', nameSimple: 'Al-Ikhlas', nameEnglish: 'The Sincerity', revelationPlace: 'makkah', versesCount: 4, bismillahPre: true },
  { id: 113, nameArabic: 'الفلق', nameSimple: 'Al-Falaq', nameEnglish: 'The Daybreak', revelationPlace: 'makkah', versesCount: 5, bismillahPre: true },
  { id: 114, nameArabic: 'الناس', nameSimple: 'An-Nas', nameEnglish: 'Mankind', revelationPlace: 'makkah', versesCount: 6, bismillahPre: true },
];

export function getChapterMetadata(id: number): Chapter {
  const found = SURAHS.find(s => s.id === id);
  if (!found) {
    throw new Error(`Surah ${id} not found in metadata catalog.`);
  }
  return found;
}

/**
 * True when the basmala precedes this surah but is not itself an ayah of it.
 *
 * Only Al-Fatihah (where the basmala *is* ayah 1) and At-Tawbah (which has none) are false.
 * Text providers prefix the basmala onto ayah 1 whenever this is true, so the provider uses
 * this same flag to know that the prefix has to be separated before the verse is indexed —
 * keeping the ornament the reader renders and the word indices it plays from one source.
 */
export function hasSeparateBasmala(surah: number): boolean {
  return SURAHS.find(chapter => chapter.id === surah)?.bismillahPre ?? false;
}
