/**
 * Arabic Lab — dual-track curriculum (levels A1–A8).
 *
 * Sits alongside the existing 10-level Tajweed ladder (`lib/learning/curriculum.ts`); nothing
 * is renumbered and no learner progress is migrated. Each level exercises up to four tracks:
 *
 *   writing  — stroke models, joins, dictation
 *   reading  — tashkeel placement, unvowelled reading
 *   grammar  — nahw (iʿrāb) and sarf (roots + awzān)
 *   register — the classical ↔ spoken bridge, always glossed in English AND Tamil
 *
 * Grammar/register lessons that teach a rule MUST state a `rulePair`: the Quranic anchor and
 * the everyday Modern Standard Arabic equivalent that drops, keeps, or reroutes the ending.
 */

import type { ArabicLabLevel, ArabicLabLesson } from './types';

const L1: ArabicLabLesson[] = [
  {
    id: 'A1-1',
    level: 'A1',
    track: 'writing',
    title: 'Pen-down order: verticals and bowls',
    titleArabic: 'تَرْتِيبُ الْقَلَمِ: الْأَلِفُ وَالْبَاءُ',
    objectiveEn: 'Trace the isolated vertical and bowl letters from the right edge, sitting on the baseline.',
    objectiveTa: 'வலது ஓரத்திலிருந்து, அடிக்கோட்டின் மேல் நிற்கும் தனி எழுத்துகளை வரையுங்கள்.',
    estimatedMinutes: 8,
    xpReward: 45,
    activities: [
      {
        id: 'A1-1-a1',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Alif',
        instructionEn: 'Start at the top right and draw a single stroke straight down to the baseline.',
        instructionTa: 'வலது மேல் மூலையிலிருந்து தொடங்கி, அடிக்கோடு வரை ஒரே இழுவையாகக் கீழே இழுக்கவும்.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'alif', form: 'isolated' },
      },
      {
        id: 'A1-1-a2',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Baa',
        instructionEn: 'Draw the shallow bowl with one stroke, then place the single dot below it.',
        instructionTa: 'ஆழமற்ற பாத்திர வளைவை ஒரே இழுவையில் வரைந்து, கீழே ஒரு புள்ளி வையுங்கள்.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'baa', form: 'isolated' },
      },
      {
        id: 'A1-1-a3',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Taa',
        instructionEn: 'Same bowl as Baa, but two dots above — the dots belong to the letter, not the bowl.',
        instructionTa: 'பா போன்ற அதே வளைவு, ஆனால் மேலே இரண்டு புள்ளிகள் — புள்ளிகள் எழுத்தின் ஒரு பகுதி.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'taa', form: 'isolated' },
      },
    ],
  },
  {
    id: 'A1-2',
    level: 'A1',
    track: 'writing',
    title: 'Dots, tails and depth',
    titleArabic: 'النُّقَطُ وَالذُّيُولُ',
    objectiveEn: 'Trace letters whose identity depends on dot count and on a descender below the baseline.',
    objectiveTa: 'புள்ளிகளின் எண்ணிக்கையும் அடிக்கோட்டுக்குக் கீழே செல்லும் வாலும் எழுத்தின் அடையாளம்.',
    estimatedMinutes: 9,
    xpReward: 45,
    activities: [
      {
        id: 'A1-2-a1',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Jeem',
        instructionEn: 'Bow the stroke down past the baseline, then add the dot in the belly of the curve.',
        instructionTa: 'வளைவை அடிக்கோட்டுக்குக் கீழே கொண்டு சென்று, வளைவின் உள்ளே புள்ளி வையுங்கள்.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'jeem', form: 'isolated' },
      },
      {
        id: 'A1-2-a2',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Dal',
        instructionEn: 'One smooth stroke: down, then a hard left turn that ends above the baseline.',
        instructionTa: 'ஒரே மென்மையான இழுவை: கீழே, பின் இடதுபக்கம் திரும்பி அடிக்கோட்டுக்கு மேல் முடியும்.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'dal', form: 'isolated' },
      },
      {
        id: 'A1-2-a3',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Noon',
        instructionEn: 'Deep bowl with a dot above, and the tail stays on the baseline.',
        instructionTa: 'ஆழமான வளைவு, மேலே ஒரு புள்ளி, வால் அடிக்கோட்டில் நிற்கும்.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'noon', form: 'isolated' },
      },
    ],
  },
];

const L2: ArabicLabLesson[] = [
  {
    id: 'A2-1',
    level: 'A2',
    track: 'reading',
    title: 'Who joins to the left?',
    titleArabic: 'الْحُرُوفُ الْمُتَّصِلَةُ',
    objectiveEn: 'Read the same letter in all four positional forms and trace the initial form.',
    objectiveTa: 'ஒரே எழுத்தை நான்கு நிலை வடிவங்களில் படித்து, தொடக்க வடிவத்தை வரையுங்கள்.',
    estimatedMinutes: 10,
    xpReward: 35,
    activities: [
      {
        id: 'A2-1-a1',
        type: 'letter_join',
        track: 'reading',
        title: 'Baa at the start of a word',
        instructionEn: 'Which form of Baa comes at the beginning, joined from the right?',
        instructionTa: 'வார்த்தையின் தொடக்கத்தில், வலது பக்கம் இணைந்து வரும் பா வடிவம் எது?',
        entryIds: ['kitab'],
        xpReward: 15,
        options: ['بـ', 'ـبـ', 'ـب', 'ب'],
        correctAnswer: 'بـ',
        explanationEn: 'At the start, Baa keeps its head and opens to the left: بـ',
        explanationTa: 'தொடக்கத்தில் பா தன் தலையைத் தக்கவைத்து இடப்பக்கம் திறக்கும்: بـ',
      },
      {
        id: 'A2-1-a2',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace the initial Baa',
        instructionEn: 'Start at the right, sweep left, and stop where the letter will be joined.',
        instructionTa: 'வலதிலிருந்து தொடங்கி இடப்பக்கம் இழுத்து, இணைப்பு நிற்கும் இடத்தில் முடிக்கவும்.',
        entryIds: ['kitab'],
        xpReward: 20,
        writing: { letterId: 'baa', form: 'initial' },
      },
    ],
  },
  {
    id: 'A2-2',
    level: 'A2',
    track: 'reading',
    title: 'The six letters that never connect',
    titleArabic: 'الْحُرُوفُ غَيْرُ الْمُتَّصِلَةِ',
    objectiveEn: 'Recognise alif, dal, dhal, raa, zay and waw, which never join the letter after them.',
    objectiveTa: 'அலிஃப், தால், தால் (த), ரா, ஸாய், வாவ் — தமக்குப் பின் வரும் எழுத்துடன் இணையாத ஆறு எழுத்துகள்.',
    estimatedMinutes: 10,
    xpReward: 35,
    activities: [
      {
        id: 'A2-2-a1',
        type: 'letter_join',
        track: 'reading',
        title: 'Spot the non-connector',
        instructionEn: 'Which letter never connects to the letter that follows it?',
        instructionTa: 'தமக்குப் பின் வரும் எழுத்துடன் எந்த எழுத்து இணையாது?',
        entryIds: ['kitab'],
        xpReward: 15,
        options: ['د', 'ب', 'م', 'ل'],
        correctAnswer: 'د',
        explanationEn: 'Dal (and dhal, raa, zay, waw, alif) never connect to the left, so the next letter starts fresh.',
        explanationTa: 'தால் (மேலும் தால், ரா, ஸாய், வாவ், அலிஃப்) இடப்பக்கம் இணையாது; அடுத்த எழுத்து புதிதாகத் தொடங்கும்.',
      },
      {
        id: 'A2-2-a2',
        type: 'letter_join',
        track: 'reading',
        title: 'Read a joined word',
        instructionEn: 'Using the letters ب ت ك, which reading is the word كِتَاب?',
        instructionTa: 'ب ت ك எழுத்துகளைப் பயன்படுத்தி, எது كِتَاب என்ற சொல்?',
        entryIds: ['kitab'],
        xpReward: 20,
        options: ['كِتَاب', 'بَاتِك', 'تَبَاكِ', 'كِبَات'],
        correctAnswer: 'كِتَاب',
        explanationEn: 'Read right to left: ك connects forward, ت connects forward, then ا then ب — كِتَاب.',
        explanationTa: 'வலமிருந்து இடமாக: ك இணையும், ت இணையும், பின் ا, பின் ب — كِتَاب.',
      },
    ],
  },
];

const L3: ArabicLabLesson[] = [
  {
    id: 'A3-1',
    level: 'A3',
    track: 'grammar',
    title: 'The nominal sentence: مُبْتَدَأ and خَبَر',
    titleArabic: 'الْجُمْلَةُ الِاسْمِيَّةُ',
    objectiveEn: 'Identify the two halves of a verbless sentence and the case each one takes.',
    objectiveTa: 'வினை இல்லாத வாக்கியத்தின் இரு பகுதிகளையும், அவற்றின் இஃராப் நிலையையும் கண்டறியுங்கள்.',
    estimatedMinutes: 12,
    xpReward: 40,
    rulePair: {
      ruleNameEn: 'Mubtadaʾ + khabar (both marfūʿ)',
      ruleNameTa: 'முப்ததா + கபர் (இரண்டும் ரஃப்)',
      classical: {
        arabic: 'ٱلْحَمْدُ لِلَّهِ',
        noteEn: 'ٱلْحَمْدُ is the mubtadaʾ: rafʿ with damma.',
        noteTa: 'ٱلْحَمْدُ முப்ததா: ரஃப் (தம்மா).',
      },
      spoken: {
        arabic: 'الصَّلَاةُ نُورٌ',
        noteEn: 'The same skeleton in speech: noun first, predicate second, no verb at all.',
        noteTa: 'பேச்சிலும் அதே அமைப்பு: முதலில் பெயர், பின் பயனிலை, வினை இல்லை.',
      },
      transferNoteEn: 'Nothing is lost in speech — only the short vowels go quiet. Learn the frame once and speak it.',
      transferNoteTa: 'பேச்சில் இழப்பு இல்லை — சிற்றுயிரொலிகள் மட்டும் அமைதியாகும். அமைப்பை ஒருமுறை கற்றால் பேசலாம்.',
    },
    activities: [
      {
        id: 'A3-1-a1',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Case of ٱلْحَمْدُ',
        instructionEn: 'In ٱلْحَمْدُ لِلَّهِ, what is the iʿrāb of ٱلْحَمْدُ?',
        instructionTa: 'ٱلْحَمْدُ لِلَّهِ இல் ٱلْحَمْدُ வின் இஃராப் என்ன?',
        entryIds: ['al-hamd', 'allah'],
        xpReward: 20,
        options: ['مرفوع بالضمة', 'منصوب بالفتحة', 'مجرور بالكسرة', 'مبني على السكون'],
        correctAnswer: 'مرفوع بالضمة',
        explanationEn: 'It is the mubtadaʾ, so it is marfūʿ with damma.',
        explanationTa: 'இது முப்ததா என்பதால் ரஃப் (தம்மா) நிலையில் உள்ளது.',
      },
      {
        id: 'A3-1-a2',
        type: 'register_compare',
        track: 'register',
        title: 'Say the same sentence aloud',
        instructionEn: 'Which spoken sentence keeps the classical noun + predicate frame?',
        instructionTa: 'குர்ஆனின் பெயர் + பயனிலை அமைப்பைத் தக்கவைக்கும் பேச்சு வாக்கியம் எது?',
        entryIds: ['salah'],
        xpReward: 20,
        options: ['الصَّلَاةُ نُورٌ', 'يُصَلِّي الرَّجُلُ', 'فِي الْمَسْجِدِ نُورٌ', 'نُورٌ الصَّلَاةَ'],
        correctAnswer: 'الصَّلَاةُ نُورٌ',
        explanationEn: 'Noun first, then its predicate — exactly the classical frame, with the endings neutralized.',
        explanationTa: 'முதலில் பெயர், பின் பயனிலை — குர்ஆன் அமைப்பே; முடிவுகள் மட்டும் அமைதியாகும்.',
      },
    ],
  },
  {
    id: 'A3-2',
    level: 'A3',
    track: 'register',
    title: 'Pointing at things in both registers',
    titleArabic: 'الْإِشَارَةُ فِي النَّسَقَيْنِ',
    objectiveEn: 'Match a Quranic demonstrative sentence with the sentence you would actually say.',
    objectiveTa: 'குர்ஆனின் சுட்டு வாக்கியத்தை, நீங்கள் உண்மையில் பேசும் வாக்கியத்துடன் பொருத்துங்கள்.',
    estimatedMinutes: 11,
    xpReward: 40,
    rulePair: {
      ruleNameEn: 'Demonstrative as mubtadaʾ, noun as khabar',
      ruleNameTa: 'சுட்டுப்பெயர் முப்ததா, பெயர் கபர்',
      classical: {
        arabic: 'ذَٰلِكَ ٱلْكِتَٰبُ',
        noteEn: 'ذلك is the mubtadaʾ; ٱلْكِتَٰبُ is its khabar, marfūʿ.',
        noteTa: 'ذلك முப்ததா; ٱلْكِتَٰبُ அதன் கபர், ரஃப்.',
      },
      spoken: {
        arabic: 'هَذَا كِتَابٌ جَدِيدٌ',
        noteEn: 'Near demonstrative this time, same frame: هَذَا + noun.',
        noteTa: 'இப்போது அண்மைச் சுட்டு, அதே அமைப்பு: هَذَا + பெயர்.',
      },
      transferNoteEn: 'ذلك / هَذَا is one of the few words where the classical and spoken forms differ only in distance, not in grammar.',
      transferNoteTa: 'ذلك / هَذَا — தூரம் மட்டுமே வேறுபாடு; இலக்கணம் மாறவில்லை.',
    },
    activities: [
      {
        id: 'A3-2-a1',
        type: 'register_compare',
        track: 'register',
        title: 'Classical → spoken',
        instructionEn: 'Which spoken sentence is the everyday equivalent of ذَٰلِكَ ٱلْكِتَٰبُ?',
        instructionTa: 'ذَٰلِكَ ٱلْكِتَٰبُ க்கு அன்றாட பேச்சு இணை எது?',
        entryIds: ['kitab'],
        xpReward: 20,
        options: ['هَذَا كِتَابٌ جَدِيدٌ', 'أَكْتُبُ بِالْقَلَمِ', 'الْكِتَابُ جَدِيدٌ هَذَا', 'كِتَابٌ هَذَا جَدِيدٌ'],
        correctAnswer: 'هَذَا كِتَابٌ جَدِيدٌ',
        explanationEn: 'Both are demonstrative + noun; speech adds an adjective and drops the case vowel.',
        explanationTa: 'இரண்டும் சுட்டு + பெயர்; பேச்சில் பெயரடை சேர்கிறது, கேஸ் உயிரொலி விழுகிறது.',
      },
      {
        id: 'A3-2-a2',
        type: 'sarf_match',
        track: 'grammar',
        title: 'Where does كِتَاب come from?',
        instructionEn: 'Which root does كِتَاب belong to?',
        instructionTa: 'كِتَاب எந்த வேரைச் சேர்ந்தது?',
        entryIds: ['kitab', 'yaktubun'],
        xpReward: 20,
        options: ['ك-ت-ب', 'ق-ل-م', 'ع-ل-م', 'ح-م-د'],
        correctAnswer: 'ك-ت-ب',
        explanationEn: 'Root ك-ت-ب on the pattern فِعَال — "that which is written".',
        explanationTa: 'வேர் ك-ت-ب, அமைப்பு فِعَال — "எழுதப்பட்டது".',
      },
    ],
  },
];

const L4: ArabicLabLesson[] = [
  {
    id: 'A4-1',
    level: 'A4',
    track: 'grammar',
    title: 'Iḍāfa: two nouns, one idea',
    titleArabic: 'الْإِضَافَةُ',
    objectiveEn: 'Read a possessive chain, mark its muḍāf ilayhi, and say it in speech.',
    objectiveTa: 'உடைமைத் தொடரைப் படித்து, முழாஃப் இலைஹியைக் குறித்து, பேச்சில் சொல்லுங்கள்.',
    estimatedMinutes: 13,
    xpReward: 60,
    rulePair: {
      ruleNameEn: 'Iḍāfa: muḍāf (no alif-lām, no tanwīn) + muḍāf ilayhi (majrūr)',
      ruleNameTa: 'இளாஃபா: முழாஃப் (அல்-உயிரொலி இல்லை) + முழாஃப் இலைஹி (ஜர்)',
      classical: {
        arabic: 'رَبِّ ٱلْعَٰلَمِينَ',
        noteEn: 'رَبِّ is majrūr as a badal; ٱلْعَٰلَمِينَ is muḍāf ilayhi, majrūr with ya.',
        noteTa: 'رَبِّ பதல் என்பதால் ஜர்; ٱلْعَٰلَمِينَ முழாஃப் இலைஹி, யாவால் ஜர்.',
      },
      spoken: {
        arabic: 'بَيْتُنَا قَرِيبٌ مِنَ الْمَسْجِدِ',
        noteEn: 'The same ownership chain survives with a pronoun: بَيْتُ + نَا.',
        noteTa: 'அதே உடைமைத் தொடர் பிரதிப்பெயருடன் நிலைக்கிறது: بَيْتُ + نَا.',
      },
      transferNoteEn: 'Iḍāfa is the single most transferable structure: speech keeps the chain, drops only the final vowel.',
      transferNoteTa: 'இளாஃபா மிகவும் கைமாற்றத்தக்க அமைப்பு: பேச்சு தொடரைத் தக்கவைத்து, இறுதி உயிரொலியை மட்டும் விடும்.',
    },
    activities: [
      {
        id: 'A4-1-a1',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Case of ٱلْعَٰلَمِينَ',
        instructionEn: 'Why does ٱلْعَٰلَمِينَ end in ya instead of kasra?',
        instructionTa: 'ٱلْعَٰلَمِينَ ஏன் கஸ்ராவுக்குப் பதிலாக யா வில் முடிகிறது?',
        entryIds: ['alamin', 'rabb'],
        xpReward: 20,
        options: ['جمع مذكر سالم مجرور بالياء', 'مفرد مجرور بالكسرة', 'منصوب بالفتحة', 'مرفوع بالواو'],
        correctAnswer: 'جمع مذكر سالم مجرور بالياء',
        explanationEn: 'A sound masculine plural marks jarr with ya — the same mechanic speech keeps as a long -īn.',
        explanationTa: 'ஒலி ஆண்பால் பன்மை ஜரை யாவால் குறிக்கும் — பேச்சிலும் -ஈன் என நிலைக்கிறது.',
      },
      {
        id: 'A4-1-a2',
        type: 'register_compare',
        track: 'register',
        title: 'Ownership in speech',
        instructionEn: 'Which spoken sentence replaces the second noun of the iḍāfa with a pronoun?',
        instructionTa: 'இளாஃபாவின் இரண்டாம் பெயரைப் பிரதிப்பெயராக மாற்றும் பேச்சு வாக்கியம் எது?',
        entryIds: ['rabb'],
        xpReward: 20,
        options: ['رَبِّي كَرِيمٌ', 'رَبُّ الْعَالَمِينَ كَرِيمٌ', 'الرَّبُّ كَرِيمٌ الْعَالَمِينَ', 'كَرِيمٌ رَبِّي'],
        correctAnswer: 'رَبِّي كَرِيمٌ',
        explanationEn: 'رَبِّي = rabb + the suffix ي. Speech prefers the suffix over a full iḍāfa chain.',
        explanationTa: 'رَبِّي = ரப் + பின்னொட்டு ய. முழு இளாஃபாவைவிட பின்னொட்டையே பேச்சு விரும்பும்.',
      },
      {
        id: 'A4-1-a3',
        type: 'spoken_build',
        track: 'register',
        title: 'Build the sentence',
        instructionEn: 'Arrange the words: my house is near the mosque.',
        instructionTa: 'சொற்களை வரிசைப்படுத்துங்கள்: என் வீடு பள்ளிவாசலுக்கு அருகில் உள்ளது.',
        entryIds: ['masjid', 'mualim'],
        xpReward: 20,
        tokens: ['بَيْتُنَا', 'قَرِيبٌ', 'مِنَ', 'الْمَسْجِدِ'],
        correctAnswer: 'بَيْتُنَا قَرِيبٌ مِنَ الْمَسْجِدِ',
        explanationEn: 'منَ governs الْمَسْجِدِ into jarr — the classical rule applied to a spoken sentence.',
        explanationTa: 'منَ என்பது الْمَسْجِدِ ஐ ஜர் நிலைக்குக் கொண்டு வரும் — பேச்சு வாக்கியத்தில் குர்ஆன் விதி.',
      },
    ],
  },
  {
    id: 'A4-2',
    level: 'A4',
    track: 'writing',
    title: 'Writing a whole word on the baseline',
    titleArabic: 'كِتَابَةُ كَلِمَةٍ كَامِلَةٍ',
    objectiveEn: 'Trace the letters that carry a word, then write what you hear.',
    objectiveTa: 'ஒரு சொல்லைத் தாங்கும் எழுத்துகளை வரைந்து, கேட்டதை எழுதுங்கள்.',
    estimatedMinutes: 11,
    xpReward: 55,
    activities: [
      {
        id: 'A4-2-a1',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Meem',
        instructionEn: 'Small closed head above the baseline, then the tail drops straight down.',
        instructionTa: 'அடிக்கோட்டுக்கு மேல் சிறிய மூடிய தலை, பின் வால் நேராகக் கீழே.',
        entryIds: [],
        xpReward: 15,
        writing: { letterId: 'meem', form: 'isolated' },
      },
      {
        id: 'A4-2-a2',
        type: 'stroke_trace',
        track: 'writing',
        title: 'Trace Kaaf in medial form',
        instructionEn: 'Write the medial form used inside كِتَاب — joined on both sides.',
        instructionTa: 'كِتَاب உள்ளே வரும் நடு வடிவத்தை எழுதுங்கள் — இரு பக்கமும் இணைந்தது.',
        entryIds: ['kitab'],
        xpReward: 15,
        writing: { letterId: 'kaaf', form: 'medial' },
      },
      {
        id: 'A4-2-a3',
        type: 'dictation',
        track: 'writing',
        title: 'Write what you hear',
        instructionEn: 'Listen to the spoken sentence and write it with full vowelling.',
        instructionTa: 'பேச்சு வாக்கியத்தைக் கேட்டு, முழு உயிரொலிகளுடன் எழுதுங்கள்.',
        entryIds: ['kitab', 'qalam'],
        xpReward: 25,
        dictationText: 'هَذَا كِتَابٌ جَدِيدٌ',
        explanationEn: 'Check three things: the tanwīn on كِتَابٌ, the long ي in جَدِيدٌ, and the dot of the ب.',
        explanationTa: 'மூன்றைச் சரிபாருங்கள்: كِتَابٌ இல் தன்வீன், جَدِيدٌ இல் நீண்ட ய, ب இன் புள்ளி.',
      },
    ],
  },
];

const L5: ArabicLabLesson[] = [
  {
    id: 'A5-1',
    level: 'A5',
    track: 'grammar',
    title: 'حُرُوفُ الْجَرّ: the prepositions that govern jarr',
    titleArabic: 'حُرُوفُ الْجَرِّ',
    objectiveEn: 'Recognise في، من، إلى، على، بـ and read the jarr they force on the noun.',
    objectiveTa: 'في، من، إلى، على، بـ ஆகியவற்றை அறிந்து, அவை ஏற்படுத்தும் ஜர் நிலையைப் படியுங்கள்.',
    estimatedMinutes: 13,
    xpReward: 40,
    rulePair: {
      ruleNameEn: 'Harf jarr + noun = majrūr (kasra, or ya for sound plurals)',
      ruleNameTa: 'ஹர்ஃப் ஜர் + பெயர் = மஜ்ரூர் (கஸ்ரா, அல்லது ஒலிப் பன்மைக்கு யா)',
      classical: {
        arabic: 'بِٱلصَّبْرِ',
        noteEn: 'بِـ makes ٱلصَّبْرِ majrūr with kasra.',
        noteTa: 'بِـ காரணமாக ٱلصَّبْرِ கஸ்ராவுடன் மஜ்ரூர்.',
      },
      spoken: {
        arabic: 'أَدْرُسُ بِصَبْرٍ',
        noteEn: 'Identical construction in speech — only the kasra is silent.',
        noteTa: 'பேச்சில் அதே அமைப்பு — கஸ்ரா மட்டும் ஒலிக்காது.',
      },
      transferNoteEn: 'This rule transfers at 100%: every preposition you learn in the mushaf works word-for-word in speech.',
      transferNoteTa: 'இந்த விதி முழுமையாகக் கைமாறும்: குர்ஆனில் கற்கும் ஒவ்வொரு முன்னிடையும் பேச்சில் அப்படியே வேலை செய்யும்.',
    },
    activities: [
      {
        id: 'A5-1-a1',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Case of ٱلْقَلَمِ',
        instructionEn: 'In عَلَّمَ بِٱلْقَلَمِ, what governs the kasra of ٱلْقَلَمِ?',
        instructionTa: 'عَلَّمَ بِٱلْقَلَمِ இல் ٱلْقَلَمِ இன் கஸ்ராவை ஆள்வது எது?',
        entryIds: ['qalam', 'allama'],
        xpReward: 20,
        options: ['حرف الجر بِـ', 'الفعل عَلَّمَ', 'الْمُبْتَدَأ', 'الإضافة'],
        correctAnswer: 'حرف الجر بِـ',
        explanationEn: 'The preposition بِـ forces jarr; the verb has no effect on it.',
        explanationTa: 'بِـ முன்னிடை ஜரை ஏற்படுத்துகிறது; வினைக்கு அதில் பங்கு இல்லை.',
      },
      {
        id: 'A5-1-a2',
        type: 'register_compare',
        track: 'register',
        title: 'Same rule, spoken sentence',
        instructionEn: 'Which spoken sentence uses the identical harf jarr construction?',
        instructionTa: 'அதே ஹர்ஃப் ஜர் அமைப்பைப் பயன்படுத்தும் பேச்சு வாக்கியம் எது?',
        entryIds: ['sabr', 'haqq'],
        xpReward: 20,
        options: ['أَدْرُسُ بِصَبْرٍ', 'الصَّبْرُ جَمِيلٌ', 'يَصْبِرُ الرَّجُلُ', 'صَبْرٌ بِالدَّرْسِ'],
        correctAnswer: 'أَدْرُسُ بِصَبْرٍ',
        explanationEn: 'بِـ + noun, exactly as in بِٱلْصَّبْرِ.',
        explanationTa: 'بِـ + பெயர்; بِٱلصَّبْرِ போலவே.',
      },
    ],
  },
  {
    id: 'A5-2',
    level: 'A5',
    track: 'register',
    title: 'Everyday sentences with جار ومجرور',
    titleArabic: 'جَارٌ وَمَجْرُورٌ فِي الْكَلَامِ',
    objectiveEn: 'Order a spoken sentence and hold a short market and prayer conversation.',
    objectiveTa: 'ஒரு பேச்சு வாக்கியத்தை ஒழுங்குசெய்து, சந்தை மற்றும் தொழுகை உரையாடலை நடத்துங்கள்.',
    estimatedMinutes: 12,
    xpReward: 60,
    rulePair: {
      ruleNameEn: 'Jarr survives word-for-word: preposition + majrūr in speech',
      ruleNameTa: 'ஜர் அப்படியே நிலைக்கும்: முன்னிடை + மஜ்ரூர் பேச்சிலும்',
      classical: {
        arabic: 'بِٱلْحَقِّ وَبِٱلصَّبْرِ',
        noteEn: 'Both nouns are majrūr because the preposition بِـ governs them.',
        noteTa: 'بِـ முன்னிடை ஆள்வதால் இரு பெயர்களும் மஜ்ரூர்.',
      },
      spoken: {
        arabic: 'أَشْتَرِي الْفَاكِهَةَ مِنَ السُّوقِ',
        noteEn: 'Everyday sentences reuse the same prepositional frame, now with مِنَ.',
        noteTa: 'அன்றாட வாக்கியங்கள் அதே முன்னிடை அமைப்பையே மீண்டும் பயன்படுத்துகின்றன — இப்போது مِنَ உடன்.',
      },
      transferNoteEn: 'Learn the frame once and reuse it everywhere; only the vocabulary changes.',
      transferNoteTa: 'அமைப்பை ஒருமுறை கற்றால் எல்லா இடத்திலும் பயன்படும்; மாறுவது சொற்கள் மட்டுமே.',
    },
    activities: [
      {
        id: 'A5-2-a1',
        type: 'spoken_build',
        track: 'register',
        title: 'Market sentence',
        instructionEn: 'Arrange: I buy fruit from the market.',
        instructionTa: 'வரிசைப்படுத்துங்கள்: நான் சந்தையில் பழம் வாங்குகிறேன்.',
        entryIds: ['suq'],
        xpReward: 20,
        tokens: ['أَشْتَرِي', 'الْفَاكِهَةَ', 'مِنَ', 'السُّوقِ'],
        correctAnswer: 'أَشْتَرِي الْفَاكِهَةَ مِنَ السُّوقِ',
        explanationEn: 'Verb first, then the object (manṣūb), then the prepositional phrase (majrūr).',
        explanationTa: 'முதலில் வினை, பின் பொருள் (நஸ்ப்), பின் முன்னிடைத் தொடர் (ஜர்).',
      },
      {
        id: 'A5-2-a2',
        type: 'dialogue_listen',
        track: 'register',
        title: 'At the market',
        instructionEn: 'Listen to the dialogue and repeat each turn aloud.',
        instructionTa: 'உரையாடலைக் கேட்டு, ஒவ்வொரு வரியையும் சத்தமாகத் திரும்பச் சொல்லுங்கள்.',
        entryIds: ['suq', 'kitab', 'qalam'],
        xpReward: 20,
        dialogId: 'd-suq',
      },
      {
        id: 'A5-2-a3',
        type: 'dialogue_listen',
        track: 'register',
        title: 'Prayer and the mosque',
        instructionEn: 'Answer the teacher using جار ومجرور with في and مِن.',
        instructionTa: 'في, مِن ஆகியவற்றுடன் ஜார் வ மஜ்ரூர் பயன்படுத்தி ஆசிரியருக்குப் பதிலளியுங்கள்.',
        entryIds: ['salah', 'masjid'],
        xpReward: 20,
        dialogId: 'd-salah',
      },
    ],
  },
];

const L6: ArabicLabLesson[] = [
  {
    id: 'A6-1',
    level: 'A6',
    track: 'grammar',
    title: 'The four case roles in one pass',
    titleArabic: 'الرَّفْعُ وَالنَّصْبُ وَالْجَرُّ',
    objectiveEn: 'Move one word through rafʿ, nasb and jarr, and read why each ending appears.',
    objectiveTa: 'ஒரே சொல்லை ரஃப், நஸ்ப், ஜர் நிலைகளில் செலுத்தி, ஒவ்வொரு முடிவுக்கான காரணத்தைப் படியுங்கள்.',
    estimatedMinutes: 14,
    xpReward: 40,
    rulePair: {
      ruleNameEn: 'One word, three endings: manṣūb object, marfūʿ subject, majrūr after a preposition',
      ruleNameTa: 'ஒரு சொல், மூன்று முடிவுகள்: நஸ்ப் பொருள், ரஃப் செய்பவர், ஜர் முன்னிடைக்குப் பின்',
      classical: {
        arabic: 'عَلَّمَ ٱلْإِنسَٰنَ',
        noteEn: 'ٱلْإِنسَٰنَ is manṣūb because it is the object of the verb.',
        noteTa: 'ٱلْإِنسَٰنَ வினையின் பொருள் என்பதால் நஸ்ப்.',
      },
      spoken: {
        arabic: 'الْإِنْسَانُ يَحْتَاجُ إِلَى الْعِلْمِ',
        noteEn: 'The same word is now marfūʿ as the subject — endings follow grammar, not the word.',
        noteTa: 'அதே சொல் இப்போது எழுவாய் என்பதால் ரஃப் — முடிவு இலக்கணத்தைப் பின்தொடரும், சொல்லை அல்ல.',
      },
      transferNoteEn: 'Spoken MSA keeps the roles but often silences the short vowels — read the role, hear the vowel only in careful speech.',
      transferNoteTa: 'பேச்சு MSA பாத்திரங்களைத் தக்கவைக்கும்; சிற்றுயிரொலிகளை அமைதியாக்கும் — கவனமான பேச்சில் மட்டுமே கேட்கும்.',
    },
    activities: [
      {
        id: 'A6-1-a1',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Object of the verb',
        instructionEn: 'In عَلَّمَ ٱلْإِنسَٰنَ, what is the iʿrāb of ٱلْإِنسَٰنَ?',
        instructionTa: 'عَلَّمَ ٱلْإِنسَٰنَ இல் ٱلْإِنسَٰنَ வின் இஃராப் என்ன?',
        entryIds: ['insan', 'allama'],
        xpReward: 20,
        options: ['منصوب بالفتحة مفعول به', 'مرفوع بالضمة فاعل', 'مجرور بالكسرة', 'مبني على الفتح'],
        correctAnswer: 'منصوب بالفتحة مفعول به',
        explanationEn: 'Directed object of عَلَّمَ → naṣb with fatha.',
        explanationTa: 'عَلَّمَ இன் நேரடிப் பொருள் → ஃபத்ஹாவுடன் நஸ்ப்.',
      },
      {
        id: 'A6-1-a2',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Marks of the plural',
        instructionEn: 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ — which sign marks the rafʿ of ٱلْمُؤْمِنُونَ?',
        instructionTa: 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ — ٱلْمُؤْمِنُونَ இன் ரஃப்பைக் குறிக்கும் அடையாளம் எது?',
        entryIds: ['muminun'],
        xpReward: 20,
        options: ['الواو', 'الضمة', 'الألف', 'الياء'],
        correctAnswer: 'الواو',
        explanationEn: 'Sound masculine plurals take waw for rafʿ, ya for nasb and jarr.',
        explanationTa: 'ஒலி ஆண்பால் பன்மை: ரஃப் = வாவ், நஸ்ப்/ஜர் = யா.',
      },
    ],
  },
  {
    id: 'A6-2',
    level: 'A6',
    track: 'reading',
    title: 'Tanwīn, and reading with the vowels removed',
    titleArabic: 'التَّنْوِينُ وَالْقِرَاءَةُ بِدُونِ تَشْكِيلٍ',
    objectiveEn: 'Place the correct ending on an unvowelled word, then read a short ayah unaided.',
    objectiveTa: 'உயிரொலிகள் இல்லாத சொல்லுக்குச் சரியான முடிவை இட்டு, ஒரு சிறு வசனத்தைத் தனியாகப் படியுங்கள்.',
    estimatedMinutes: 12,
    xpReward: 60,
    rulePair: {
      ruleNameEn: 'Tanwīn follows the grammatical role: -an (naṣb), -un (rafʿ), -in (jarr)',
      ruleNameTa: 'தன்வீன் இலக்கணப் பாத்திரத்தைப் பின்தொடரும்: -அன் (நஸ்ப்), -உன் (ரஃப்), -இன் (ஜர்)',
      classical: {
        arabic: 'مَعَ ٱلْعُسْرِ يُسْرًا',
        noteEn: 'يُسْرًا is the delayed khabar of إِنَّ, so it carries tanwīn fatha.',
        noteTa: 'يُسْرًا إِنَّ இன் பிந்திய கபர் என்பதால் தன்வீன் ஃபத்ஹா பெறுகிறது.',
      },
      spoken: {
        arabic: 'أُرِيدُ يُسْرًا فِي الْعَمَلِ',
        noteEn: 'Speech writes the tanwīn in careful speech but usually does not sound the final -n.',
        noteTa: 'கவனமான பேச்சில் தன்வீன் எழுதப்படும்; இறுதி -ன் ஒலி பொதுவாகக் கேட்காது.',
      },
      transferNoteEn: 'Train the eye: strip the vowels and the role is still recoverable from word order and prepositions.',
      transferNoteTa: 'கண்ணைப் பயிற்றுவியுங்கள்: உயிரொலிகளை நீக்கினாலும் சொல் வரிசையும் முன்னிடைகளும் பாத்திரத்தை வெளிப்படுத்தும்.',
    },
    activities: [
      {
        id: 'A6-2-a1',
        type: 'tashkeel_placement',
        track: 'reading',
        title: 'Which ending is correct?',
        instructionEn: 'Choose the correctly vowelled form of يُسْر as the khabar of إِنَّ.',
        instructionTa: 'إِنَّ இன் கபராக வரும் يُسْر இன் சரியான உயிரொலி வடிவைத் தேர்ந்தெடுங்கள்.',
        entryIds: ['yusr', 'usr'],
        xpReward: 20,
        options: ['يُسْرًا', 'يُسْرٌ', 'يُسْرٍ', 'يُسْرَ'],
        correctAnswer: 'يُسْرًا',
        explanationEn: 'Khabar of إِنَّ is manṣūb → tanwīn fatha.',
        explanationTa: 'إِنَّ இன் கபர் நஸ்ப் → தன்வீன் ஃபத்ஹா.',
      },
      {
        id: 'A6-2-a2',
        type: 'register_compare',
        track: 'register',
        title: 'Keep the case, drop the sound',
        instructionEn: 'Which spoken sentence shows the same word in a different case?',
        instructionTa: 'அதே சொல் வேறு இஃராப் நிலையில் வரும் பேச்சு வாக்கியம் எது?',
        entryIds: ['ahad'],
        xpReward: 20,
        options: ['لَا أَحَدَ فِي الْبَيْتِ', 'أَحَدٌ فِي الْبَيْتِ', 'فِي الْبَيْتِ أَحَدٌ هَذَا', 'هَذَا أَحَدٌ الْبَيْتِ'],
        correctAnswer: 'لَا أَحَدَ فِي الْبَيْتِ',
        explanationEn: 'لَا governs أَحَد into naṣb — the same word, a different governing word.',
        explanationTa: 'لَا என்பது أَحَد ஐ நஸ்ப் நிலைக்குக் கொண்டுவரும் — ஒரே சொல், வேறு ஆளும் சொல்.',
      },
      {
        id: 'A6-2-a3',
        type: 'dialogue_listen',
        track: 'register',
        title: 'Talking about daily recitation',
        instructionEn: 'Hold the conversation about reading and memorising.',
        instructionTa: 'ஓதுதல், மனனம் பற்றிய உரையாடலை நடத்துங்கள்.',
        entryIds: ['sabr', 'usr', 'yusr'],
        xpReward: 20,
        dialogId: 'd-quran',
      },
    ],
  },
];

const L7: ArabicLabLesson[] = [
  {
    id: 'A7-1',
    level: 'A7',
    track: 'grammar',
    title: 'Root and pattern (الجَذْرُ وَالْوَزْن)',
    titleArabic: 'الْجَذْرُ وَالْوَزْنُ',
    objectiveEn: 'Read a root, name its pattern, and predict the words built from it.',
    objectiveTa: 'ஒரு வேரைப் படித்து, அதன் அமைப்பைக் கூறி, அதிலிருந்து பிறக்கும் சொற்களை ஊகியுங்கள்.',
    estimatedMinutes: 14,
    xpReward: 40,
    rulePair: {
      ruleNameEn: 'Sarf family: عَلَّمَ (form II verb) → مُعَلِّم (participle) → تَعْلِيم (verbal noun)',
      ruleNameTa: 'சர்ஃப் குடும்பம்: عَلَّمَ (வடிவம் II வினை) → مُعَلِّم (பெயரெச்சம்) → تَعْلِيم (வினைப்பெயர்)',
      classical: {
        arabic: 'عَلَّمَ ٱلْإِنسَٰنَ',
        noteEn: 'Form II doubles the middle radical to give a causative sense: to make someone know.',
        noteTa: 'வடிவம் II நடு எழுத்தை இரட்டித்து காரணப் பொருளைத் தரும்: ஒருவரை அறியச் செய்தல்.',
      },
      spoken: {
        arabic: 'الْمُعَلِّمُ يُعَلِّمُ الطُّلَّابَ',
        noteEn: 'Everyday speech leans on the same family — the teacher, the act of teaching, the taught.',
        noteTa: 'அன்றாட பேச்சும் இதே குடும்பத்தையே சார்ந்திருக்கும் — ஆசிரியர், கற்பித்தல், கற்பவர்.',
      },
      transferNoteEn: 'Once you can name a pattern you stop memorising single words and start recognising families.',
      transferNoteTa: 'ஒரு அமைப்பைப் பெயரிடக் கற்றால், தனிச் சொற்களை மனனம் செய்வது நிற்கும்; சொற்குடும்பங்களை அறியத் தொடங்குவீர்கள்.',
    },
    activities: [
      {
        id: 'A7-1-a1',
        type: 'sarf_match',
        track: 'grammar',
        title: 'Name the pattern',
        instructionEn: 'Which word sits on the pattern مُفَعِّل?',
        instructionTa: 'مُفَعِّل என்ற அமைப்பில் அமைந்த சொல் எது?',
        entryIds: ['mualim', 'allama'],
        xpReward: 20,
        options: ['مُعَلِّم', 'عَلَّمَ', 'عَالِم', 'تَعْلِيم'],
        correctAnswer: 'مُعَلِّم',
        explanationEn: 'Form II active participle: مُ + doubled middle radical + kasra + ل.',
        explanationTa: 'வடிவம் II செய்பெயரெச்சம்: مُ + இரட்டை நடு எழுத்து + கஸ்ரா + ل.',
      },
      {
        id: 'A7-1-a2',
        type: 'sarf_match',
        track: 'grammar',
        title: 'Same root, different job',
        instructionEn: 'كِتَاب، كَاتِب، مَكْتُوب — which one is the passive participle (مَفْعُول)?',
        instructionTa: 'كِتَاب، كَاتِب، مَكْتُوب — எது செயப்படுபொருள் பெயரெச்சம் (مَفْعُول)?',
        entryIds: ['kitab', 'yaktubun'],
        xpReward: 20,
        options: ['مَكْتُوب', 'كِتَاب', 'كَاتِب', 'كِتَابَة'],
        correctAnswer: 'مَكْتُوب',
        explanationEn: 'مَفْعُول = the thing acted upon, i.e. that which has been written.',
        explanationTa: 'مَفْعُول = செய்யப்பட்டது, அதாவது எழுதப்பட்டது.',
      },
    ],
  },
  {
    id: 'A7-2',
    level: 'A7',
    track: 'register',
    title: 'Verb families in real speech',
    titleArabic: 'الْأَفْعَالُ فِي الْكَلَامِ',
    objectiveEn: 'Use form I and form II verbs in the past and present inside a lesson conversation.',
    objectiveTa: 'ஒரு பாட உரையாடலில் வடிவம் I மற்றும் II வினைகளை கடந்த/நிகழ்காலத்தில் பயன்படுத்துங்கள்.',
    estimatedMinutes: 13,
    xpReward: 60,
    rulePair: {
      ruleNameEn: 'A pattern learned from the mushaf becomes a word family you can speak',
      ruleNameTa: 'குர்ஆனில் கற்ற அமைப்பு, நீங்கள் பேசக்கூடிய சொற்குடும்பமாக மாறும்',
      classical: {
        arabic: 'يَكْتُبُونَ ٱلْكِتَٰبَ',
        noteEn: 'Verb on the pattern يَفْعُلُونَ with its manṣūb object.',
        noteTa: 'يَفْعُلُونَ அமைப்பில் வினை, நஸ்ப் நிலையில் பொருள்.',
      },
      spoken: {
        arabic: 'هُمْ يَكْتُبُونَ الدَّرْسَ',
        noteEn: 'Same verb, same object slot — the lesson changes, the structure does not.',
        noteTa: 'அதே வினை, அதே பொருள் இடம் — பாடம் மாறுகிறது, அமைப்பு மாறவில்லை.',
      },
      transferNoteEn: 'Drill the pattern, not the sentence: يَكْتُبُونَ → يَقْرَأُونَ → يَدْرُسُونَ.',
      transferNoteTa: 'வாக்கியத்தை அல்ல, அமைப்பைப் பயிற்றுவியுங்கள்: يَكْتُبُونَ → يَقْرَأُونَ → يَدْرُسُونَ.',
    },
    activities: [
      {
        id: 'A7-2-a1',
        type: 'spoken_build',
        track: 'register',
        title: 'They write the lesson',
        instructionEn: 'Arrange: they write the lesson.',
        instructionTa: 'வரிசைப்படுத்துங்கள்: அவர்கள் பாடத்தை எழுதுகிறார்கள்.',
        entryIds: ['yaktubun'],
        xpReward: 20,
        tokens: ['هُمْ', 'يَكْتُبُونَ', 'الدَّرْسَ'],
        correctAnswer: 'هُمْ يَكْتُبُونَ الدَّرْسَ',
        explanationEn: 'الدرس is manṣūb as the object even though speech will not sound the fatha.',
        explanationTa: 'பேச்சில் ஃபத்ஹா ஒலிக்காவிட்டாலும் الدَّرْسَ பொருள் என்பதால் நஸ்ப்.',
      },
      {
        id: 'A7-2-a2',
        type: 'dictation',
        track: 'writing',
        title: 'Write the teacher sentence',
        instructionEn: 'Write down the sentence with full vowelling.',
        instructionTa: 'வாக்கியத்தை முழு உயிரொலிகளுடன் எழுதுங்கள்.',
        entryIds: ['mualim', 'talib', 'allama'],
        xpReward: 20,
        dictationText: 'الْمُعَلِّمُ يُعَلِّمُ الطُّلَّابَ',
        explanationEn: 'Watch the shaddah on the middle radical of both يُعَلِّمُ and الْمُعَلِّمُ.',
        explanationTa: 'يُعَلِّمُ, الْمُعَلِّمُ இரண்டிலும் நடு எழுத்தின் ஷத்தாவைக் கவனியுங்கள்.',
      },
      {
        id: 'A7-2-a3',
        type: 'dialogue_listen',
        track: 'register',
        title: 'A reading lesson',
        instructionEn: 'Take the learner role: ask about a word you do not understand.',
        instructionTa: 'மாணவர் பாத்திரத்தை ஏற்று, புரியாத சொல்லைப் பற்றிக் கேளுங்கள்.',
        entryIds: ['kitab', 'qalam', 'talib'],
        xpReward: 20,
        dialogId: 'd-dars',
      },
    ],
  },
];

const L8: ArabicLabLesson[] = [
  {
    id: 'A8-1',
    level: 'A8',
    track: 'grammar',
    title: 'The verbal sentence (الجُمْلَة الفِعْلِيَّة)',
    titleArabic: 'الْجُمْلَةُ الْفِعْلِيَّةُ',
    objectiveEn: 'Read verb-first sentences, then speak the same content with subject-first word order.',
    objectiveTa: 'வினை முதலில் வரும் வாக்கியங்களைப் படித்து, பின் எழுவாய் முதலில் வரும் பேச்சு வரிசையில் சொல்லுங்கள்.',
    estimatedMinutes: 14,
    xpReward: 65,
    rulePair: {
      ruleNameEn: 'Classical VSO: verb + fāʿil (marfūʿ) + object (manṣūb) — speech often shifts to SVO',
      ruleNameTa: 'குர்ஆன் வரிசை VSO: வினை + ஃபாஇல் (ரஃப்) + பொருள் (நஸ்ப்) — பேச்சு பெரும்பாலும் SVO ஆகும்',
      classical: {
        arabic: 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ',
        noteEn: 'أَفْلَحَ first, then its fāʿil ٱلْمُؤْمِنُونَ, marfūʿ with waw.',
        noteTa: 'முதலில் أَفْلَحَ, பின் அதன் ஃபாஇல் ٱلْمُؤْمِنُونَ, வாவால் ரஃப்.',
      },
      spoken: {
        arabic: 'الْمُؤْمِنُونَ إِخْوَةٌ',
        noteEn: 'The same community topic, said as a nominal sentence — a very common speech preference.',
        noteTa: 'அதே கருத்து, பெயர்ச்சொல் வாக்கியமாக — பேச்சில் மிகவும் பொதுவான விருப்பம்.',
      },
      transferNoteEn: 'Both word orders are valid MSA. Knowing which one speech prefers is what stops you sounding like a book.',
      transferNoteTa: 'இரண்டு வரிசைகளும் செல்லுபடியான MSA. பேச்சு எதை விரும்புகிறது என்பதை அறிந்தால் புத்தகம் போல ஒலிக்காதீர்கள்.',
    },
    activities: [
      {
        id: 'A8-1-a1',
        type: 'irab_parse',
        track: 'grammar',
        title: 'Who is the fāʿil?',
        instructionEn: 'In قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ, which word is the fāʿil?',
        instructionTa: 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ இல் ஃபாஇல் எந்தச் சொல்?',
        entryIds: ['muminun'],
        xpReward: 20,
        options: ['ٱلْمُؤْمِنُونَ', 'أَفْلَحَ', 'قَدْ', 'لَيْسَ فِي الْآيَةِ فَاعِلٌ'],
        correctAnswer: 'ٱلْمُؤْمِنُونَ',
        explanationEn: 'The doer follows the verb and is marfūʿ — here with waw because it is a sound plural.',
        explanationTa: 'செய்பவர் வினைக்குப் பின் வந்து ரஃப் பெறும் — ஒலிப் பன்மை என்பதால் வாவால்.',
      },
      {
        id: 'A8-1-a2',
        type: 'register_compare',
        track: 'register',
        title: 'Which ending survives speech?',
        instructionEn: 'For the verb يَلِدْ (jazm with sukun), what happens in speech?',
        instructionTa: 'يَلِدْ வினைக்கு (சுகூன் ஜஸ்ம்), பேச்சில் என்ன நடக்கும்?',
        entryIds: ['yalid'],
        xpReward: 20,
        options: [
          'السكون يبقى كما هو',
          'يُحذف السكون فيُصبح يَلِدُ',
          'تُضاف فتحة فيُصبح يَلِدَ',
          'يُصبح يَاءً ممدودة',
        ],
        correctAnswer: 'السكون يبقى كما هو',
        explanationEn: 'Jazm with sukun is intrinsic, so it stays; only short case vowels of nouns get neutralized.',
        explanationTa: 'சுகூன் ஜஸ்ம் சொல்லின் இயல்பு, மாறாது; பெயர்களின் சிற்றுயிரொலிகள் மட்டுமே அமைதியாகும்.',
      },
      {
        id: 'A8-1-a3',
        type: 'spoken_build',
        track: 'register',
        title: 'Say it the way people speak',
        instructionEn: 'Arrange the spoken-order sentence: the teacher teaches the students.',
        instructionTa: 'பேச்சு வரிசையில் வாக்கியத்தை ஒழுங்குசெய்யுங்கள்: ஆசிரியர் மாணவர்களுக்குக் கற்பிக்கிறார்.',
        entryIds: ['allama', 'mualim'],
        xpReward: 25,
        tokens: ['الْمُعَلِّمُ', 'يُعَلِّمُ', 'الطُّلَّابَ'],
        correctAnswer: 'الْمُعَلِّمُ يُعَلِّمُ الطُّلَّابَ',
        explanationEn: 'Subject first, then the verb and its object — the SVO order speech prefers.',
        explanationTa: 'முதலில் எழுவாய், பின் வினையும் பொருளும் — பேச்சு விரும்பும் SVO வரிசை.',
      },
    ],
  },
  {
    id: 'A8-2',
    level: 'A8',
    track: 'register',
    title: 'Speaking with confidence',
    titleArabic: 'التَّحَدُّثُ بِثِقَةٍ',
    objectiveEn: 'Run two full conversations: introductions, and home and family.',
    objectiveTa: 'இரண்டு முழு உரையாடல்களை நடத்துங்கள்: அறிமுகம், வீடும் குடும்பமும்.',
    estimatedMinutes: 12,
    xpReward: 55,
    rulePair: {
      ruleNameEn: 'Speaking means choosing which endings to keep',
      ruleNameTa: 'பேசுதல் என்றால் எந்த முடிவுகளைத் தக்கவைப்பது என்பதைத் தேர்ந்தெடுப்பது',
      classical: {
        arabic: 'الصَّلَاةُ نُورٌ لِلْمُؤْمِنِينَ',
        noteEn: 'Damma, tanwīn and jarr ya — all three endings are written and recited.',
        noteTa: 'தம்மா, தன்வீன், ஜர் யா — மூன்று முடிவுகளும் எழுதப்பட்டு ஓதப்படுகின்றன.',
      },
      spoken: {
        arabic: 'الصَّلَاةُ نُورٌ لِلْمُؤْمِنِينَ',
        noteEn: 'The long endings survive; only the short case vowels go quiet in fast speech.',
        noteTa: 'நீண்ட முடிவுகள் நிலைக்கும்; வேகமான பேச்சில் சிற்றுயிரொலிகள் மட்டும் அமைதியாகும்.',
      },
      transferNoteEn: 'Fluent speech is produced, not withheld: say the sentence, then refine the endings with the coach.',
      transferNoteTa: 'சரளமான பேச்சு தயக்கம் இல்லாமல் வரும்: முதலில் சொல்லுங்கள், பின் ஆசிரியருடன் முடிவுகளைச் செம்மைப்படுத்துங்கள்.',
    },
    activities: [
      {
        id: 'A8-2-a1',
        type: 'dialogue_listen',
        track: 'register',
        title: 'Introduce yourself',
        instructionEn: 'Answer every teacher turn out loud without reading the transliteration.',
        instructionTa: 'ஒலிபெயர்ப்பைப் பார்க்காமல், ஆசிரியரின் ஒவ்வொரு வரிக்கும் சத்தமாகப் பதிலளியுங்கள்.',
        entryIds: ['allah', 'al-hamd'],
        xpReward: 20,
        dialogId: 'd-tahiyya',
      },
      {
        id: 'A8-2-a2',
        type: 'dialogue_listen',
        track: 'register',
        title: 'Home and family',
        instructionEn: 'Describe your own family using the same iḍāfa and jarr patterns.',
        instructionTa: 'அதே இளாஃபா, ஜர் அமைப்புகளைப் பயன்படுத்தி உங்கள் குடும்பத்தை விவரியுங்கள்.',
        entryIds: ['talib', 'masjid', 'kitab'],
        xpReward: 20,
        dialogId: 'd-bayt',
      },
      {
        id: 'A8-2-a3',
        type: 'dictation',
        track: 'writing',
        title: 'Final dictation',
        instructionEn: 'Write the sentence, then read it back with the endings you chose.',
        instructionTa: 'வாக்கியத்தை எழுதி, நீங்கள் தேர்ந்த முடிவுகளுடன் அதைத் திரும்பப் படியுங்கள்.',
        entryIds: ['muminun', 'salah'],
        xpReward: 15,
        dictationText: 'الصَّلَاةُ نُورٌ لِلْمُؤْمِنِينَ',
        explanationEn: 'Three checks: the damma on الصَّلَاةُ, the tanwīn on نُورٌ, and the jarr ya in لِلْمُؤْمِنِينَ.',
        explanationTa: 'மூன்று சரிபார்ப்புகள்: الصَّلَاةُ இல் தம்மா, نُورٌ இல் தன்வீன், لِلْمُؤْمِنِينَ இல் ஜர் யா.',
      },
    ],
  },
];

export const ARABIC_LAB_LEVELS: readonly ArabicLabLevel[] = [
  {
    id: 'A1',
    index: 1,
    title: 'Pen, baseline, isolated letters',
    titleArabic: 'الْقَلَمُ وَالسَّطْرُ وَالْحُرُوفُ الْمُفْرَدَةُ',
    summaryEn: 'Motor skills first: pen-down order for isolated letters, sitting on the Arabic baseline, right to left.',
    summaryTa: 'முதலில் கைப்பயிற்சி: அரபு அடிக்கோட்டின் மேல், வலமிருந்து இடமாக, தனி எழுத்துகளின் பேனா வரிசை.',
    tracks: ['writing'],
    requiredXp: 0,
    lessons: L1,
  },
  {
    id: 'A2',
    index: 2,
    title: 'Joining letters and reading real words',
    titleArabic: 'اتِّصَالُ الْحُرُوفِ وَقِرَاءَةُ الْكَلِمَاتِ',
    summaryEn: 'Letters change shape when they join. Learn who connects to the left and who never does.',
    summaryTa: 'எழுத்துகள் இணையும்போது வடிவம் மாறும். இடப்பக்கம் இணைபவை, இணையாதவை எவை எனக் கற்போம்.',
    tracks: ['reading', 'writing'],
    requiredXp: 120,
    lessons: L2,
  },
  {
    id: 'A3',
    index: 3,
    title: 'The nominal sentence',
    titleArabic: 'الْجُمْلَةُ الِاسْمِيَّةُ',
    summaryEn: 'A statement with no verb: read it in the mushaf, then say it in Modern Standard Arabic.',
    summaryTa: 'வினை இல்லாத வாக்கியம்: குர்ஆனில் படித்து, பின் நவீன நிலையான அரபியில் பேசுவோம்.',
    tracks: ['grammar', 'register'],
    requiredXp: 250,
    lessons: L3,
  },
  {
    id: 'A4',
    index: 4,
    title: 'Iḍāfa and writing whole words',
    titleArabic: 'الْإِضَافَةُ وَكِتَابَةُ الْكَلِمَاتِ',
    summaryEn: 'Iḍāfa chains two nouns into one idea; speech often replaces the second noun with a pronoun.',
    summaryTa: 'இளாஃபா இரு பெயர்ச்சொற்களை ஒரே கருத்தாக இணைக்கும்; பேச்சில் இரண்டாம் பெயர் பிரதிப்பெயராகலாம்.',
    tracks: ['grammar', 'register', 'writing'],
    requiredXp: 400,
    lessons: L4,
  },
  {
    id: 'A5',
    index: 5,
    title: 'Prepositions and the genitive',
    titleArabic: 'حُرُوفُ الْجَرِّ',
    summaryEn: 'Prepositions govern jarr. The same جار ومجرور pattern powers everyday speech.',
    summaryTa: 'முன்னிடைச் சொற்கள் ஜர் நிலையை ஆளும். இதே அமைப்பு அன்றாட பேச்சையும் இயக்குகிறது.',
    tracks: ['grammar', 'register'],
    requiredXp: 600,
    lessons: L5,
  },
  {
    id: 'A6',
    index: 6,
    title: 'The four cases and reading unvowelled',
    titleArabic: 'الْإِعْرَابُ وَالْقِرَاءَةُ بِدُونِ تَشْكِيلٍ',
    summaryEn: 'Learn the case roles, place tanwīn correctly, then read the same ayah with vowels removed.',
    summaryTa: 'இஃராப் பாத்திரங்களைக் கற்று, தன்வீனை சரியாக இட்டு, உயிரொலிகள் இல்லாமல் அதே வசனத்தைப் படியுங்கள்.',
    tracks: ['grammar', 'reading', 'register'],
    requiredXp: 850,
    lessons: L6,
  },
  {
    id: 'A7',
    index: 7,
    title: 'Roots, patterns and verb families',
    titleArabic: 'الْجُذُورُ وَالْأَوْزَانُ',
    summaryEn: 'Every word is a root plus a pattern. See the pattern once and a whole family opens up.',
    summaryTa: 'ஒவ்வொரு சொல்லும் ஒரு வேரும் ஒரு அமைப்பும். அமைப்பைக் கண்டால் ஒரு சொற்குடும்பம் திறக்கும்.',
    tracks: ['grammar', 'register', 'writing'],
    requiredXp: 1150,
    lessons: L7,
  },
  {
    id: 'A8',
    index: 8,
    title: 'Verbal sentences and real conversation',
    titleArabic: 'الْجُمْلَةُ الْفِعْلِيَّةُ وَالْمُحَادَثَةُ',
    summaryEn: 'Put it together: verb-first Quranic syntax, spoken word order, and the endings you keep or drop.',
    summaryTa: 'இணைத்துப் பயன்படுத்துவோம்: குர்ஆன் வினை-முதல் அமைப்பு, பேச்சு வரிசை, தக்கவைக்கும்/விடும் முடிவுகள்.',
    tracks: ['grammar', 'register', 'writing'],
    requiredXp: 1500,
    lessons: L8,
  },
];

/** Total XP available from the Arabic Lab track. */
export const ARABIC_LAB_TOTAL_XP: number = ARABIC_LAB_LEVELS.reduce(
  (levelSum, level) => levelSum + level.lessons.reduce((lessonSum, lesson) => lessonSum + lesson.xpReward, 0),
  0
);

export const ARABIC_LAB_LESSONS: readonly ArabicLabLesson[] = ARABIC_LAB_LEVELS.flatMap(
  (level) => level.lessons
);

const LESSON_BY_ID = new Map(ARABIC_LAB_LESSONS.map((lesson) => [lesson.id, lesson]));

export function getArabicLabLesson(id: string): ArabicLabLesson | undefined {
  return LESSON_BY_ID.get(id);
}

export function getArabicLabLevelOfLesson(lessonId: string): ArabicLabLevel | undefined {
  return ARABIC_LAB_LEVELS.find((level) => level.lessons.some((lesson) => lesson.id === lessonId));
}
