/**
 * Arabic Lab — spoken-register dialogs (Modern Standard Arabic only).
 *
 * Design contract: dialogs never mix registers. Every turn is fully vowelled MSA with an
 * English gloss and a Tamil bridge gloss, so the learner produces the same language they
 * have been reading in the classical track — just with the case endings neutralized.
 */

import type { ArabicDialog } from './types';

export const ARABIC_DIALOGS: readonly ArabicDialog[] = [
  {
    id: 'd-tahiyya',
    titleEn: 'Greeting and introductions',
    titleTa: 'வணக்கமும் அறிமுகமும்',
    titleArabic: 'التَّحِيَّةُ وَالتَّعَارُفُ',
    scenarioEn: 'Meeting a teacher for the first time at the study circle.',
    scenarioTa: 'பாடசாலையில் ஆசிரியரை முதல் முறையாகச் சந்திக்கிறீர்கள்.',
    targetEntryIds: ['allah', 'al-hamd'],
    turns: [
      {
        speaker: 'learner',
        arabicMsa: 'السَّلَامُ عَلَيْكُمْ',
        transliteration: 'as-salāmu ʿalaykum',
        glossEn: 'Peace be upon you.',
        glossTa: 'உங்கள் மீது சாந்தி உண்டாகட்டும்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللَّهِ',
        transliteration: 'wa-ʿalaykumu s-salāmu wa-raḥmatu llāh',
        glossEn: 'And upon you be peace, and the mercy of God.',
        glossTa: 'உங்கள் மீதும் சாந்தியும் அல்லாஹ்வின் அருளும் உண்டாகட்டும்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'كَيْفَ حَالُكَ؟',
        transliteration: 'kayfa ḥāluk',
        glossEn: 'How are you?',
        glossTa: 'எப்படி இருக்கிறீர்கள்?',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'أَنَا بِخَيْرٍ، الْحَمْدُ لِلَّهِ',
        transliteration: 'anā bi-khayr, al-ḥamdu lillāh',
        glossEn: 'I am well, praise be to God.',
        glossTa: 'நான் நன்றாக இருக்கிறேன், அல்லாஹ்வுக்கே புகழ்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'مَا اسْمُكَ؟',
        transliteration: 'mā ismuk',
        glossEn: 'What is your name?',
        glossTa: 'உங்கள் பெயர் என்ன?',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'اسْمِي أَحْمَدُ، وَأَنْتَ؟',
        transliteration: 'ismī aḥmad, wa-anta',
        glossEn: 'My name is Ahmad, and you?',
        glossTa: 'என் பெயர் அஹ்மத், நீங்கள்?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'اسْمِي يُوسُفُ، تَشَرَّفْتُ بِمَعْرِفَتِكَ',
        transliteration: 'ismī yūsuf, tasharraftu bi-maʿrifatik',
        glossEn: 'My name is Yusuf, pleased to meet you.',
        glossTa: 'என் பெயர் யூஸுஃப், உங்களைச் சந்தித்ததில் மகிழ்ச்சி.',
      },
    ],
  },
  {
    id: 'd-dars',
    titleEn: 'In the classroom',
    titleTa: 'வகுப்பறையில்',
    titleArabic: 'فِي الصَّفِّ',
    scenarioEn: 'A one-to-one Arabic reading lesson.',
    scenarioTa: 'தனிப்பட்ட அரபு வாசிப்புப் பாடம்.',
    targetEntryIds: ['kitab', 'qalam', 'mualim', 'talib', 'madrasa', 'yaktubun'],
    turns: [
      {
        speaker: 'teacher',
        arabicMsa: 'هَلْ عِنْدَكَ كِتَابٌ؟',
        transliteration: 'hal ʿindaka kitāb',
        glossEn: 'Do you have a book?',
        glossTa: 'உங்களிடம் புத்தகம் இருக்கிறதா?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'نَعَمْ، عِنْدِي كِتَابٌ وَقَلَمٌ',
        transliteration: 'naʿam, ʿindī kitābun wa-qalam',
        glossEn: 'Yes, I have a book and a pen.',
        glossTa: 'ஆம், என்னிடம் ஒரு புத்தகமும் பேனாவும் உள்ளன.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'اقْرَأِ الصَّفْحَةَ الْأُولَى مِنْ فَضْلِكَ',
        transliteration: 'iqraʾi ṣ-ṣafḥata l-ūlā min faḍlik',
        glossEn: 'Please read the first page.',
        glossTa: 'தயவுசெய்து முதல் பக்கத்தைப் படியுங்கள்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'لَا أَفْهَمُ هَذِهِ الْكَلِمَةَ',
        transliteration: 'lā afhamu hādhihi l-kalima',
        glossEn: 'I do not understand this word.',
        glossTa: 'இந்த வார்த்தை எனக்குப் புரியவில்லை.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'هَذِهِ كَلِمَةٌ سَهْلَةٌ، سَأَشْرَحُهَا',
        transliteration: 'hādhihi kalimatun sahla, sa-ashraḥuhā',
        glossEn: 'This word is easy, I will explain it.',
        glossTa: 'இந்த வார்த்தை எளிதானது, நான் அதை விளக்குகிறேன்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'شُكْرًا يَا مُعَلِّمِي',
        transliteration: 'shukran yā muʿallimī',
        glossEn: 'Thank you, my teacher.',
        glossTa: 'நன்றி, என் ஆசிரியரே.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'اكْتُبْ هَذِهِ الْكَلِمَاتِ فِي دَفْتَرِكَ',
        transliteration: 'uktub hādhihi l-kalimāti fī daftarik',
        glossEn: 'Write these words in your notebook.',
        glossTa: 'இந்த வார்த்தைகளை உங்கள் நோட்டில் எழுதுங்கள்.',
      },
    ],
  },
  {
    id: 'd-quran',
    titleEn: 'Daily Quran reading',
    titleTa: 'தினசரி குர்ஆன் ஓதுதல்',
    titleArabic: 'الْقِرَاءَةُ الْيَوْمِيَّةُ',
    scenarioEn: 'Talking about a daily recitation habit and one verse.',
    scenarioTa: 'தினசரி ஓதும் பழக்கம் மற்றும் ஒரு வசனம் பற்றிய உரையாடல்.',
    targetEntryIds: ['sabr', 'usr', 'yusr', 'kitab'],
    turns: [
      {
        speaker: 'teacher',
        arabicMsa: 'هَلْ تَقْرَأُ الْقُرْآنَ كُلَّ يَوْمٍ؟',
        transliteration: 'hal taqraʾu l-qurʾāna kulla yawm',
        glossEn: 'Do you read the Quran every day?',
        glossTa: 'நீங்கள் தினமும் குர்ஆன் ஓதுகிறீர்களா?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'نَعَمْ، أَقْرَأُ فِي الصَّبَاحِ وَالْمَسَاءِ',
        transliteration: 'naʿam, aqraʾu fī ṣ-ṣabāḥi wa-l-masāʾ',
        glossEn: 'Yes, I read in the morning and the evening.',
        glossTa: 'ஆம், காலையிலும் மாலையிலும் ஓதுகிறேன்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'مَا مَعْنَى كَلِمَةِ الصَّبْرِ؟',
        transliteration: 'mā maʿnā kalimati ṣ-ṣabr',
        glossEn: 'What is the meaning of the word patience?',
        glossTa: 'பொறுமை என்ற வார்த்தையின் பொருள் என்ன?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'الصَّبْرُ يَعْنِي أَنْ تَنْتَظِرَ بِهُدُوءٍ',
        transliteration: 'aṣ-ṣabru yaʿnī an tantaẓira bi-hudūʾ',
        glossEn: 'Patience means to wait calmly.',
        glossTa: 'பொறுமை என்றால் அமைதியாகக் காத்திருப்பது.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'أَحْسَنْتَ، مَعَ الْعُسْرِ يُسْرٌ',
        transliteration: 'aḥsanta, maʿa l-ʿusri yusr',
        glossEn: 'Well done — with hardship there is ease.',
        glossTa: 'நன்று — சிரமத்துடன் வசதியும் உண்டு.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'سَأَحْفَظُ هَذِهِ الْآيَةَ الْيَوْمَ',
        transliteration: 'sa-aḥfaẓu hādhihi l-āyata l-yawm',
        glossEn: 'I will memorize this verse today.',
        glossTa: 'இன்று இந்த வசனத்தை மனனம் செய்வேன்.',
      },
    ],
  },
  {
    id: 'd-salah',
    titleEn: 'Prayer and the mosque',
    titleTa: 'தொழுகையும் பள்ளிவாசலும்',
    titleArabic: 'الصَّلَاةُ وَالْمَسْجِدُ',
    scenarioEn: 'Talking about where and when you pray.',
    scenarioTa: 'எங்கே, எப்போது தொழுகிறீர்கள் என்பது பற்றி.',
    targetEntryIds: ['salah', 'masjid', 'muminun'],
    turns: [
      {
        speaker: 'teacher',
        arabicMsa: 'أَيْنَ تُصَلِّي؟',
        transliteration: 'ayna tuṣallī',
        glossEn: 'Where do you pray?',
        glossTa: 'எங்கே தொழுகிறீர்கள்?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'أُصَلِّي فِي الْمَسْجِدِ مَعَ جِيرَانِي',
        transliteration: 'uṣallī fī l-masjidi maʿa jīrānī',
        glossEn: 'I pray in the mosque with my neighbours.',
        glossTa: 'நான் என் அண்டை வீட்டாருடன் பள்ளிவாசலில் தொழுகிறேன்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'مَتَى تُصَلِّي الْعَصْرَ؟',
        transliteration: 'matā tuṣallī l-ʿaṣr',
        glossEn: 'When do you pray ʿAsr?',
        glossTa: 'அஸர் தொழுகையை எப்போது தொழுகிறீர்கள்?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'أُصَلِّي الْعَصْرَ بَعْدَ الظُّهْرِ',
        transliteration: 'uṣallī l-ʿaṣra baʿda ẓ-ẓuhr',
        glossEn: 'I pray ʿAsr after Ẓuhr.',
        glossTa: 'நான் லுஹருக்குப் பின் அஸர் தொழுகிறேன்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'الصَّلَاةُ نُورٌ لِلْمُؤْمِنِينَ',
        transliteration: 'aṣ-ṣalātu nūrun lil-muʾminīn',
        glossEn: 'Prayer is light for the believers.',
        glossTa: 'தொழுகை நம்பிக்கையாளர்களுக்கு ஒளியாகும்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'أُرِيدُ أَنْ أُصَلِّيَ فِي الصَّفِّ الْأَوَّلِ',
        transliteration: 'urīdu an uṣalliya fī ṣ-ṣaffi l-awwal',
        glossEn: 'I want to pray in the first row.',
        glossTa: 'முதல் வரிசையில் தொழ விரும்புகிறேன்.',
      },
    ],
  },
  {
    id: 'd-bayt',
    titleEn: 'At home with the family',
    titleTa: 'வீட்டில் குடும்பத்துடன்',
    titleArabic: 'فِي الْبَيْتِ مَعَ الْأُسْرَةِ',
    scenarioEn: 'Introducing family members and describing the house.',
    scenarioTa: 'குடும்ப உறுப்பினர்களை அறிமுகப்படுத்தி வீட்டை விவரிக்கிறீர்கள்.',
    targetEntryIds: ['mualim', 'talib', 'masjid', 'kitab'],
    turns: [
      {
        speaker: 'teacher',
        arabicMsa: 'مَنْ هَذَا؟',
        transliteration: 'man hādhā',
        glossEn: 'Who is this?',
        glossTa: 'இவர் யார்?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'هَذَا أَخِي، هُوَ طَالِبٌ فِي الْجَامِعَةِ',
        transliteration: 'hādhā akhī, huwa ṭālibun fī l-jāmiʿa',
        glossEn: 'This is my brother; he is a university student.',
        glossTa: 'இவர் என் சகோதரர்; அவர் பல்கலைக்கழக மாணவர்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'أَيْنَ بَيْتُكُمْ؟',
        transliteration: 'ayna baytukum',
        glossEn: 'Where is your house?',
        glossTa: 'உங்கள் வீடு எங்கே?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'بَيْتُنَا قَرِيبٌ مِنَ الْمَسْجِدِ',
        transliteration: 'baytunā qarībun mina l-masjid',
        glossEn: 'Our house is near the mosque.',
        glossTa: 'எங்கள் வீடு பள்ளிவாசலுக்கு அருகில் உள்ளது.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'هَلْ عِنْدَكُمْ مَكْتَبَةٌ؟',
        transliteration: 'hal ʿindakum maktaba',
        glossEn: 'Do you have a library?',
        glossTa: 'உங்களிடம் ஒரு நூலகம் இருக்கிறதா?',
      },
      {
        speaker: 'learner',
        arabicMsa: 'نَعَمْ، عِنْدَنَا كُتُبٌ كَثِيرَةٌ',
        transliteration: 'naʿam, ʿindanā kutubun kathīra',
        glossEn: 'Yes, we have many books.',
        glossTa: 'ஆம், எங்களிடம் நிறைய புத்தகங்கள் உள்ளன.',
      },
    ],
  },
  {
    id: 'd-suq',
    titleEn: 'At the market',
    titleTa: 'சந்தையில்',
    titleArabic: 'فِي السُّوقِ',
    scenarioEn: 'Buying a book and a pen.',
    scenarioTa: 'ஒரு புத்தகமும் பேனாவும் வாங்குகிறீர்கள்.',
    targetEntryIds: ['suq', 'kitab', 'qalam'],
    turns: [
      {
        speaker: 'learner',
        arabicMsa: 'بِكَمْ هَذَا الْكِتَابُ؟',
        transliteration: 'bikam hādhā l-kitāb',
        glossEn: 'How much is this book?',
        glossTa: 'இந்தப் புத்தகம் எவ்வளவு?',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'بِعَشَرَةِ دَرَاهِمَ',
        transliteration: 'bi-ʿasharati darāhim',
        glossEn: 'For ten dirhams.',
        glossTa: 'பத்து திர்கம்.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'أُرِيدُ قَلَمًا وَاحِدًا أَيْضًا',
        transliteration: 'urīdu qalaman wāḥidan ayḍan',
        glossEn: 'I also want one pen.',
        glossTa: 'எனக்கு ஒரு பேனாவும் வேண்டும்.',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'تَفَضَّلْ، هَذَا قَلَمٌ جَيِّدٌ',
        transliteration: 'tafaḍḍal, hādhā qalamun jayyid',
        glossEn: 'Here you are, this is a good pen.',
        glossTa: 'இதோ, இது ஒரு நல்ல பேனா.',
      },
      {
        speaker: 'learner',
        arabicMsa: 'هَلْ عِنْدَكَ دَفَاتِرُ؟',
        transliteration: 'hal ʿindaka dafātir',
        glossEn: 'Do you have notebooks?',
        glossTa: 'உங்களிடம் நோட்டுகள் இருக்கிறதா?',
      },
      {
        speaker: 'teacher',
        arabicMsa: 'نَعَمْ، الدَّفَاتِرُ عَلَى الْيَمِينِ',
        transliteration: 'naʿam, ad-dafātiru ʿalā l-yamīn',
        glossEn: 'Yes, the notebooks are on the right.',
        glossTa: 'ஆம், நோட்டுகள் வலதுபுறம் உள்ளன.',
      },
    ],
  },
];

const DIALOG_BY_ID = new Map(ARABIC_DIALOGS.map((dialog) => [dialog.id, dialog]));

export function getArabicDialog(id: string): ArabicDialog | undefined {
  return DIALOG_BY_ID.get(id);
}
